# Generated by Django 5.0.1 on 2024-02-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmodel",
            name="departement",
            field=models.CharField(
                choices=[
                    ("1", "INFORMATIQUE INDUSTRIELLE "),
                    ("2", "iNFORMATIQUE DE GESTION"),
                ],
                max_length=10,
            ),
        ),
    ]
